kind = "web"
previewPath = "/"
title = "Neuralix Dashboard"
version = "1.0.0"
id = "artifacts/neuralix"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23133

[services.development]
run = "pnpm --filter @workspace/neuralix run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/neuralix", "run", "build" ]
publicDir = "artifacts/neuralix/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23133"
BASE_PATH = "/"
